import type { NextPage } from 'next'
import Link from 'next/link';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LinkButton from '../components/linkButton';
import Slogan from '../components/slogan';

const Home: NextPage = () => {
  return (
    <div className={styles.main}>
      <Head>
        <title> Chia </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    <h1> JIA Sun</h1>
    <Slogan/>
    <LinkButton href = "/about" text= "About"/>
    <LinkButton href = "/blogs" text= "Tech Blog" />
    <LinkButton href = "https://twitter.com/sk_196844" text= "Twitter" />
    <LinkButton href = "https://github.com/sun-jacobi" text= "Github" />
    <LinkButton href = "https://www.linkedin.com/in/sun42/" text= "Linkedin" /> 
    </div>
  )
}

export default Home
